id: A4F50348B
title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen Chokgyur
  Lingpa'
type: translation
pechas:
- I88A02B05
- I9E4B3C01
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:33.642487
  last_modified_at: 2023-01-04 11:33:33.642492
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I88A02B05/87A3: '4043'
  I9E4B3C01/3325: '4043'
